/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankdummyserver;

import com.asac.function.impl.BERTLV_Impl;
import com.asac.test.ABDServer;
import com.asac.test.BankServer;
import com.function.StringFunction;
import com.muamalat.iso8583.PackagerFactory;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jpos.iso.ISOException;
import org.jpos.iso.ISOMsg;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author herrysuganda
 */
public class MainSimmulator extends javax.swing.JFrame {

    /**
     * Creates new form MainSimmulator
     */
    public MainSimmulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtiso = new javax.swing.JPanel();
        txtRef = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        txtBit14 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBit2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBit52 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBit35 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtBit22 = new javax.swing.JTextField();
        txtBit100 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBit55 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtRef.setText("1");

        jLabel1.setText("STAN");

        jButton5.setText("signon");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton22.setText("Send payment WAY4");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("Send void to WAY4");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jLabel4.setText("Bit 14");

        jLabel5.setText("bit 2");

        txtBit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBit2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Bit 52");

        jLabel7.setText("Bit 35");

        jButton6.setText("signon from client");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel9.setText("Bit 22");

        javax.swing.GroupLayout txtisoLayout = new javax.swing.GroupLayout(txtiso);
        txtiso.setLayout(txtisoLayout);
        txtisoLayout.setHorizontalGroup(
            txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtisoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtBit35)
                        .addComponent(txtRef, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addComponent(txtBit2)
                        .addComponent(txtBit52))
                    .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtBit14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                        .addComponent(txtBit22, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        txtisoLayout.setVerticalGroup(
            txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtisoLayout.createSequentialGroup()
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtisoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBit14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBit22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(6, 6, 6))
                    .addGroup(txtisoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(txtBit35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(txtisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBit52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)))
        );

        jLabel8.setText("Bit 100");

        jLabel10.setText("Bit 55");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBit55, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBit100, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(218, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBit100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBit55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        try {

            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
//            jangan dihapus, payment untuk tartun mesin atm bank lain, kartu BMI

//            msg.setMTI("0200");
//            msg.set(2, txtBit2.getText());
//            msg.set(3, "011000");
//            msg.set(4, "000010000000");
//            msg.set(7, "0623165759");
//            msg.set(11, "000654");
//            msg.set(12, "235735");
//            msg.set(13, "0623");
//            msg.set(14, txtBit14.getText());
//            msg.set(15, "0624");
//            msg.set(18, "6011");
//            msg.set(22, "121");
//            msg.set(25, "00");
//            msg.set(32, "000008");
//            msg.set(35, txtBit35.getText());
//            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
//            msg.set(41, "S1AW1E5D");
//            msg.set(42, "0000000S1AW1E5D");
//            msg.set(43, "CILEDUGCBD  PTUGBTARO TANGERANGM NS  ID ");
//            msg.set(49, "360");
//            msg.set(52, txtBit52.getText());
//H2H_ATMBERSA: 11:13:37:20 |Dumping ISO Message. Type: 0200
//H2H_ATMBERSA: 11:13:37:20 |Source CID 0, Destination CID 0
//H2H_ATMBERSA: 11:13:37:20 |000:H2HBRSMA.ISO
//H2H_ATMBERSA: 11:13:37:20 |001:1
//H2H_ATMBERSA: 11:13:37:20 |002:5221840063046552
//H2H_ATMBERSA: 11:13:37:20 |003:401000
//H2H_ATMBERSA: 11:13:37:20 |004:000010000000
//H2H_ATMBERSA: 11:13:37:20 |007:0702012813
//H2H_ATMBERSA: 11:13:37:20 |011:000001
//H2H_ATMBERSA: 11:13:37:20 |012:175813
//H2H_ATMBERSA: 11:13:37:20 |013:0701
//H2H_ATMBERSA: 11:13:37:20 |015:0701
//H2H_ATMBERSA: 11:13:37:20 |018:6011
//H2H_ATMBERSA: 11:13:37:20 |022:021
//H2H_ATMBERSA: 11:13:37:20 |025:00
//H2H_ATMBERSA: 11:13:37:20 |032:2
//H2H_ATMBERSA: 11:13:37:20 |035:5221840063046552=24002
//H2H_ATMBERSA: 11:13:37:20 |037:175813000001
//H2H_ATMBERSA: 11:13:37:20 |041:00001902
//H2H_ATMBERSA: 11:13:37:20 |043:BRI ATM BERSAMA SIMULATOR               
//H2H_ATMBERSA: 11:13:37:20 |048:FIRST 7890MIDDLE 890LAST 67890123             GENEROUS PEOPLE, SANG DERMAWAN
//H2H_ATMBERSA: 11:13:37:20 |049:360
//H2H_ATMBERSA: 11:13:37:20 |052:96D950525223DA3B
//H2H_ATMBERSA: 11:13:37:20 |100:002
//H2H_ATMBERSA: 11:13:37:20 |102:840063046552
//H2H_ATMBERSA: 11:13:37:20 |103:3010030036
//H2H_ATMBERSA: 11:13:37:20 |125:2
//H2H_ATMBERSA: 11:13:37:20 |127:147


//MTID	0200
//000	H2HRNTIS.ISO
//001	1
//002	6019234005117685
//003	401000
//004	000016000000
//007	0706154609
//011	010345
//012	224609
//013	0706
//017	0706
//022	051
//032	22
//035	6019234005117685=26022014135034000000
//037	003528      
//041	6459            
//043	JL. GATOT SUBROTO KM. TANGERANG       ID
//048	A                       40000036000000000000
//049	360
//052	3E00D028601B0800
//055	82025400950580000480005F2A0203605F3401019A032107069C01409F02060000160000009F03060000000000009F101C0101A000000000901E62BD00000000000000000000000000000000009F1A0203609F260814DB8627ABDE655B9F3602000B9F37042994575D
//055.82	5400
//055.95	8000048000
//055.5F2A	0360
//055.5F34	01
//055.9A	210706
//055.9C	40
//055.9F02	000016000000
//055.9F03	000000000000
//055.9F10	0101A000000000901E62BD0000000000000000000000000000000000
//055.9F1A	0360
//055.9F26	14DB8627ABDE655B
//055.9F36	000B
//055.9F37	2994575D
//060	CN01CN01+000
//103	5530054294
//126	& 0000200292! R100270 014SYARAH NABILLA FIRDAIS                                                                                                                      000                                                                                                      10                    


//            msg.setMTI("0200");
//            msg.set(2, txtBit2.getText());
//            msg.set(3, "401000");
//            msg.set(4, "000010000000");
//            msg.set(7, "0706154609");
//            msg.set(11, "010345");
//            msg.set(12, "224609");
//            msg.set(13, "0706");
//            msg.set(17, "0706");
//            msg.set(22, txtBit22.getText());
//            msg.set(32, "22");
//            msg.set(35, txtBit35.getText());
//            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
//            msg.set(41, "6459            ");
//            msg.set(43, "JL. GATOT SUBROTO KM. TANGERANG       ID");
//            msg.set(48, "A                       40000036000000000000");
//            msg.set(49, "360");
//            msg.set(52, txtBit52.getText());
//            msg.set(60, "CN01CN01+000");
//            msg.set(103, "5530054294");
//            msg.set(126, "& 0000200292! R100270 014SYARAH NABILLA FIRDAIS                                                                                                                      000                                                                                                      10                    ");
//
//            ABDServer.getInstance().sendMessage("ISO015000071"+new String(msg.pack()));




//void
            msg.setMTI("0200");
            msg.set(3, "020000");
            msg.set(4, "000729910000");
            msg.set(7, "1020145318");
            msg.set(11, "200082");
            msg.set(12, "192820");
            msg.set(13, "1020");
            msg.set(15, "1020");
            msg.set(17, "1020");
            msg.set(18, "5941");
            msg.set(22, txtBit22.getText());
            msg.set(32, "9");
            msg.set(33, "360004");
            msg.set(35, txtBit35.getText());
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            msg.set(41, "14710592        ");
            msg.set(42, "147105921234567");
            msg.set(43, "ZARA PLAZA IND/ZR01   -            ID ID");
            msg.set(48, "I001");
            msg.set(49, "360");
            msg.set(95, "000000000000000000000000000000000000000000");
            msg.set(123, "00000051850000000003");

ABDServer.getInstance().sendMessage("ISO005000060"+new String(msg.pack())+".");
//            ABDServer.getInstance().sendMessage(new String(msg.pack()));

        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        try {
            // TODO add your handling code here:
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());

//            msg.setMTI("0200");
////            msg.set(2, "5221840063046552");
//            msg.set(2, txtBit2.getText());
//            msg.set(3, "391000");
//            msg.set(4, "001053399500");
//            msg.set(7, "0412055749");
//            //            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
//            msg.set(11, "028619");
//            msg.set(12, "125749");
//            //            msg.set(12, StringFunction.getCurrentTimeHHmmsss());
//            msg.set(13, "0412");
//            //            msg.set(13, StringFunction.getCurrentDateMMDD());
//            msg.set(15, "0412");
//            msg.set(18, "6017");
//            msg.set(22, "011");
//            msg.set(25, "00");
//            msg.set(32, "002");
//            msg.set(35, "5221840063046552=24002");
//            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
//            msg.set(41, "00001902");
//            msg.set(42, "300157273308508");
//            msg.set(43, "BRI ATM BERSAMA SIMULATOR               ");
//            msg.set(48, "                              88                                            ");
//            msg.set(49, "360");
//            msg.set(52, "D844098FE22408C9");
//            msg.set(100, "002");
//            msg.set(102, "");
////            msg.set(103, "8072030000000002");
//            msg.set(103, txtBit14.getText());
//            
//            msg.set(125, "2");
//            msg.set(127, "147");
//H2H_ATMBERSA: 10:55:50:45 |002:5221840063046552
//H2H_ATMBERSA: 10:55:50:45 |003:391000
//H2H_ATMBERSA: 10:55:50:45 |004:000010000000
//H2H_ATMBERSA: 10:55:50:45 |007:0702011026
//H2H_ATMBERSA: 10:55:50:45 |011:000000
//H2H_ATMBERSA: 10:55:50:45 |012:174026
//H2H_ATMBERSA: 10:55:50:45 |013:0701
//H2H_ATMBERSA: 10:55:50:45 |015:0701
//H2H_ATMBERSA: 10:55:50:45 |018:6011
//H2H_ATMBERSA: 10:55:50:45 |022:021
//H2H_ATMBERSA: 10:55:50:45 |025:00
//H2H_ATMBERSA: 10:55:50:45 |032:2
//H2H_ATMBERSA: 10:55:50:45 |035:5221840063046552=24002
//H2H_ATMBERSA: 10:55:50:45 |037:174026000000
//H2H_ATMBERSA: 10:55:50:45 |041:00001902
//H2H_ATMBERSA: 10:55:50:45 |043:BRI ATM BERSAMA SIMULATOR               
//H2H_ATMBERSA: 10:55:50:45 |048:                              123                                           
//H2H_ATMBERSA: 10:55:50:45 |049:360
//H2H_ATMBERSA: 10:55:50:45 |052:96D950525223DA3B
//H2H_ATMBERSA: 10:55:50:45 |100:002
//H2H_ATMBERSA: 10:55:50:45 |102:
//H2H_ATMBERSA: 10:55:50:45 |103:3010030036
//H2H_ATMBERSA: 10:55:50:45 |125:3
//H2H_ATMBERSA: 10:55:50:45 |127:147

//H2H_RINTIS  : 14:35:30:05 |000:H2HRNTIS.ISO
//H2H_RINTIS  : 14:35:30:05 |001:1
//H2H_RINTIS  : 14:35:30:05 |002:6019001514133648
//H2H_RINTIS  : 14:35:30:05 |003:321000
//H2H_RINTIS  : 14:35:30:05 |004:000021000000
//H2H_RINTIS  : 14:35:30:05 |007:0703045003
//H2H_RINTIS  : 14:35:30:05 |011:000006
//H2H_RINTIS  : 14:35:30:05 |012:212003
//H2H_RINTIS  : 14:35:30:05 |013:0702
//H2H_RINTIS  : 14:35:30:05 |017:0702
//H2H_RINTIS  : 14:35:30:05 |032:2
//H2H_RINTIS  : 14:35:30:05 |035:6019001514133648=49121201188910235000
//H2H_RINTIS  : 14:35:30:05 |037:212009      
//H2H_RINTIS  : 14:35:30:05 |041:TRML014700000001
//H2H_RINTIS  : 14:35:30:05 |043:PRIMA ISSUER SIMULATOR                  
//H2H_RINTIS  : 14:35:30:05 |048:MUAMALAT SHARING GROUP  40000036000000000000
//H2H_RINTIS  : 14:35:30:05 |049:360
//H2H_RINTIS  : 14:35:30:05 |052:B264C5DB049390BB
//H2H_RINTIS  : 14:35:30:05 |060:BMI0PRIM+730
//H2H_RINTIS  : 14:35:30:05 |103:3010030036
//H2H_RINTIS  : 14:35:30:05 |126:& 0000200292! R100270 147                                                                                                                                            NO DESCRIPTION                                                                                           10                    


//000	NPGPRIMA.ISO
//001	1
//003	000000
//004	000729910000
//007	1020122820
//011	017357
//012	192820
//013	1020
//015	1020
//017	1020
//018	5941
//022	051
//032	9
//033	360004
//035	4890254000923811=24072014819784300000
//037	000000000003
//041	10124577        
//042	000100210331245
//043	ZARA PLAZA IND/ZR01   -            ID ID
//048	I001
//049	360
//052	2A7809BF983E204E
//055	82025400950542000488005F2A0203605F3401019A032210209C01009F02060007299100009F03060000000000009F101C0101A0000000006E46CB8B00000000000000000000000000000000009F1A0203609F2608314476CB97C511E29F360200A19F37041445ACF59F2701809F34030200009F3303E0F0C89F3501228407A0000006021010
//055.82	5400
//055.95	4200048800
//055.5F2A	0360
//055.5F34	01
//055.9A	221020
//055.9C	00
//055.9F02	000729910000
//055.9F03	000000000000
//055.9F10	0101A0000000006E46CB8B0000000000000000000000000000000000
//055.9F1A	0360
//055.9F26	314476CB97C511E2
//055.9F36	00A1
//055.9F37	1445ACF5
//055.9F27	80
//055.9F34	020000
//055.9F33	E0F0C8
//055.9F35	22
//055.84	A0000006021010
//123	00000051850000005185


//payment
            msg.setMTI("0200");
            msg.set(3, "000000");
            msg.set(4, "000729910000");
            msg.set(7, "1020122820");
            msg.set(11, "017357");
            msg.set(12, "192820");
            msg.set(13, "1020");
            msg.set(15, "1020");
            msg.set(17, "1020");
            msg.set(18, "5941");
            msg.set(22, txtBit22.getText());
            msg.set(32, "9");
            msg.set(33, "360004");            
            msg.set(35, txtBit35.getText());
            msg.set(37, StringFunction.pad(txtRef.getText(), 12, "0", "Right"));
            msg.set(41, "14710592        ");
            msg.set(42, "147105921234567");
            msg.set(43, "ZARA PLAZA IND/ZR01   -            ID ID");
            msg.set(48, "I001");
            msg.set(49, "360");
            msg.set(52, txtBit52.getText());
//            msg.set(55, txtBit55.getText());
            msg.set(123, "00000051850000005185");

            

            
            
            ABDServer.getInstance().sendMessage("ISO005000060"+new String(msg.pack())+".");
//            ABDServer.getInstance().sendMessage(new String(msg.pack()));
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtRef.setText(String.valueOf(1 + Long.parseLong(txtRef.getText())));
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //        String msgHexa = "60608300080110303801000EC1040431100000000000000020046110200009010008373130353932323030343631323030343631303031343731303539323134373130353932313233343536370042373734303030343132360D0A4D617277616E2050726979616E6120202020202020202020202020202020002030303030303030303043373030353038323535360006323030303639";

        try {
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            msg.setMTI("0800");
            msg.set(7, "0622004345");
            msg.set(11, "000001");
            msg.set(48, "0111002111S00360");
            msg.set(70, "001");
            ABDServer.getInstance().sendMessage("ISO015000060"+new String(msg.pack())+".");
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtBit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBit2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
//        0800822000000000000004000000000000001213062246486267001
        try {
//            untuk edc
//            ISOMsg msg = new ISOMsg();
//            msg.setPackager(PackagerFactory.getPackager());
//            msg.setMTI("0800");
//            msg.set(7, "0708102815");
//            msg.set(11, "000001");
//            msg.set(48, "0111002111S00360");
//            msg.set(70, "001");
//            BankServer.getInstance().sendMessage("ISO005000060"+new String(msg.pack()));
            
            
            
            
            ISOMsg msg = new ISOMsg();
            msg.setPackager(PackagerFactory.getPackager());
            //signon
            msg.setMTI("0800");
            msg.set(7, StringFunction.getGMTCurrentDateMMDDHHMMSS());
            msg.set(11, "486268");
            msg.set(70, "001");
            ABDServer.getInstance().sendMessage(new String(msg.pack()));
            
            
            
        } catch (ISOException ex) {
            Logger.getLogger(MainSimmulator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSimmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSimmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSimmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSimmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSimmulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBit100;
    private javax.swing.JTextField txtBit14;
    private javax.swing.JTextField txtBit2;
    private javax.swing.JTextField txtBit22;
    private javax.swing.JTextField txtBit35;
    private javax.swing.JTextField txtBit52;
    private javax.swing.JTextField txtBit55;
    private javax.swing.JTextField txtRef;
    private javax.swing.JPanel txtiso;
    // End of variables declaration//GEN-END:variables
}
